// nextjs_backup/components/navbar.tsx
"use client"

import Link from "next/link"
import { usePathname } from "next/navigation"
import { Home, Search, MessageCircle, User, LogOut, GraduationCap } from "lucide-react"
import { cn } from "@/lib/utils"

const navItems = [
  { href: "/home", label: "Home", icon: Home },
  { href: "/search", label: "Search", icon: Search },
  { href: "/chat", label: "Messages", icon: MessageCircle },
  { href: "/profile", label: "Profile", icon: User },
]

export function Navbar() {
  const pathname = usePathname()

  return (
    <nav className="sticky top-0 z-50 w-full bg-accent text-accent-foreground shadow-lg">
      <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
        <Link href="/home" className="flex items-center gap-2">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-white p-1 border border-border/20 shadow-sm">
            <img src="/logo.png" alt="TutorMX Logo" className="h-full w-full object-contain" />
          </div>
          <span className="text-xl font-bold">TutorMX</span>
        </Link>

        <div className="hidden items-center gap-1 md:flex">
          {navItems.map((item) => {
            const Icon = item.icon
            const isActive = pathname === item.href
            return (
              <Link
                key={item.href}
                href={item.href}
                className={cn(
                  "flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-colors",
                  isActive
                    ? "bg-primary text-primary-foreground"
                    : "hover:bg-white/10"
                )}
              >
                <Icon className="h-4 w-4" />
                {item.label}
              </Link>
            )
          })}
        </div>

        <div className="flex items-center gap-4">
          <Link
            href="/"
            className="flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-colors hover:bg-white/10"
          >
            <LogOut className="h-4 w-4" />
            <span className="hidden sm:inline">Logout</span>
          </Link>
        </div>
      </div>

      {/* Mobile Navigation */}
      <div className="fixed bottom-0 left-0 right-0 z-50 flex items-center justify-around border-t border-white/10 bg-accent py-2 md:hidden">
        {navItems.map((item) => {
          const Icon = item.icon
          const isActive = pathname === item.href
          return (
            <Link
              key={item.href}
              href={item.href}
              className={cn(
                "flex flex-col items-center gap-1 rounded-lg px-3 py-1.5 text-xs transition-colors",
                isActive
                  ? "text-primary"
                  : "text-accent-foreground/70 hover:text-accent-foreground"
              )}
            >
              <Icon className="h-5 w-5" />
              {item.label}
            </Link>
          )
        })}
      </div>
    </nav>
  )
}

// frontend/src/components/layout/Navbar.vue
<script setup>
import { useRoute } from 'vue-router'
import { Home, Search, MessageCircle, User, LogOut } from '@lucide/vue'
import { cn } from '@/lib/utils'

const route = useRoute()

const navItems = [
  { href: "/home", label: "Home", icon: Home },
  { href: "/search", label: "Search", icon: Search },
  { href: "/chat", label: "Messages", icon: MessageCircle },
  { href: "/profile", label: "Profile", icon: User },
]
</script>

<template>
  <nav class="sticky top-0 z-50 w-full bg-zinc-950 border-b border-white/10">
    <div class="mx-auto flex h-20 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
      <router-link to="/home" class="flex items-center gap-3 transition-opacity hover:opacity-80">
        <img src="/logo.png" alt="TutorMX Logo" class="h-12 w-auto rounded-md bg-white p-1" />
        <span class="text-2xl font-bold tracking-tight text-white">TutorMX</span>
      </router-link>

      <!-- Desktop Navigation -->
      <div class="hidden items-center gap-8 md:flex">
        <router-link
          v-for="item in navItems"
          :key="item.href"
          :to="item.href"
          :class="cn(
            'text-base font-medium transition-colors hover:text-primary',
            route.path === item.href
              ? 'text-primary'
              : 'text-zinc-400'
          )"
        >
          {{ item.label }}
        </router-link>
      </div>

      <div class="flex items-center gap-4">
        <router-link
          to="/"
          class="flex items-center gap-2 rounded-full px-4 py-2 text-sm font-medium transition-colors bg-white/10 text-white hover:bg-white/20"
        >
          <LogOut class="h-4 w-4" />
          <span class="hidden sm:inline">Logout</span>
        </router-link>
      </div>
    </div>

    <!-- Mobile Navigation -->
    <div class="fixed bottom-0 left-0 right-0 z-50 flex items-center justify-around border-t border-border bg-background/95 backdrop-blur py-2 md:hidden">
      <router-link
        v-for="item in navItems"
        :key="item.href"
        :to="item.href"
        :class="cn(
          'flex flex-col items-center gap-1 rounded-lg px-3 py-1.5 text-[10px] font-medium transition-colors',
          route.path === item.href
            ? 'text-primary'
            : 'text-muted-foreground hover:text-foreground'
        )"
      >
        <component :is="item.icon" class="h-5 w-5" />
        {{ item.label }}
      </router-link>
    </div>
  </nav>
</template>
